// <auto-generated />
using System;
using GoBest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoBest.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250812212423_SyncTicketCountSnapshot")]
    partial class SyncTicketCountSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoBest.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_time")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ItineraryId")
                        .HasColumnType("bigint")
                        .HasColumnName("itinerary_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TicketCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("ticket_count");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("booking_pkey");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.BookingLeg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<long?>("SeatTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("seat_type_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("booking_leg_pkey");

                    b.HasIndex("SeatTypeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "BookingId", "ServiceId" }, "booking_leg_booking_id_service_id_key")
                        .IsUnique();

                    b.ToTable("booking_leg", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("city_pkey");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("IataCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iata_code");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("company_pkey");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.CompanyMaintainer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("company_maintainer_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex(new[] { "UserId", "CompanyId" }, "company_maintainer_user_id_company_id_key")
                        .IsUnique();

                    b.ToTable("company_maintainer", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.Itinerary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("DestCityId")
                        .HasColumnType("bigint")
                        .HasColumnName("dest_city_id");

                    b.Property<long?>("OriginCityId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_city_id");

                    b.Property<DateTime>("SearchTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("search_time")
                        .HasDefaultValueSql("now()");

                    b.Property<TimeSpan?>("TotalDuration")
                        .HasColumnType("interval")
                        .HasColumnName("total_duration");

                    b.Property<short?>("TotalLegs")
                        .HasColumnType("smallint")
                        .HasColumnName("total_legs");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("itinerary_pkey");

                    b.HasIndex("DestCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("UserId");

                    b.ToTable("itinerary", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.ItineraryLeg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ItineraryId")
                        .HasColumnType("bigint")
                        .HasColumnName("itinerary_id");

                    b.Property<short>("LegOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("leg_order");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<long?>("SeatTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("seat_type_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("itinerary_leg_pkey");

                    b.HasIndex("SeatTypeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "ItineraryId", "LegOrder" }, "itinerary_leg_itinerary_id_leg_order_key")
                        .IsUnique();

                    b.ToTable("itinerary_leg", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.SeatType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("price_multiplier");

                    b.HasKey("Id")
                        .HasName("seat_type_pkey");

                    b.ToTable("seat_type", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_time");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_time");

                    b.Property<long?>("DestStationId")
                        .HasColumnType("bigint")
                        .HasColumnName("dest_station_id");

                    b.Property<long?>("OriginStationId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_station_id");

                    b.Property<int?>("SalesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sales_count");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("service_code");

                    b.Property<bool?>("Sold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sold");

                    b.HasKey("Id")
                        .HasName("service_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DestStationId");

                    b.HasIndex("OriginStationId");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.ServiceSeatInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Available")
                        .HasColumnType("integer")
                        .HasColumnName("available");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<long?>("SeatTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("seat_type_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("service_seat_inventory_pkey");

                    b.HasIndex("SeatTypeId");

                    b.HasIndex(new[] { "ServiceId", "SeatTypeId" }, "service_seat_inventory_service_id_seat_type_id_key")
                        .IsUnique();

                    b.ToTable("service_seat_inventory", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("StationType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("station_type");

                    b.HasKey("Id")
                        .HasName("station_pkey");

                    b.HasIndex("CityId");

                    b.ToTable("station", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex(new[] { "Email" }, "user_email_key")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GoBest.Models.Booking", b =>
                {
                    b.HasOne("GoBest.Models.Itinerary", "Itinerary")
                        .WithMany("Bookings")
                        .HasForeignKey("ItineraryId")
                        .HasConstraintName("booking_itinerary_id_fkey");

                    b.HasOne("GoBest.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_user_id_fkey");

                    b.Navigation("Itinerary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoBest.Models.BookingLeg", b =>
                {
                    b.HasOne("GoBest.Models.Booking", "Booking")
                        .WithMany("BookingLegs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_leg_booking_id_fkey");

                    b.HasOne("GoBest.Models.SeatType", "SeatType")
                        .WithMany("BookingLegs")
                        .HasForeignKey("SeatTypeId")
                        .HasConstraintName("booking_leg_seat_type_id_fkey");

                    b.HasOne("GoBest.Models.Service", "Service")
                        .WithMany("BookingLegs")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("booking_leg_service_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("SeatType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GoBest.Models.CompanyMaintainer", b =>
                {
                    b.HasOne("GoBest.Models.Company", "Company")
                        .WithMany("CompanyMaintainers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("company_maintainer_company_id_fkey");

                    b.HasOne("GoBest.Models.User", "User")
                        .WithMany("CompanyMaintainers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("company_maintainer_user_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoBest.Models.Itinerary", b =>
                {
                    b.HasOne("GoBest.Models.City", "DestCity")
                        .WithMany("ItineraryDestCities")
                        .HasForeignKey("DestCityId")
                        .HasConstraintName("itinerary_dest_city_id_fkey");

                    b.HasOne("GoBest.Models.City", "OriginCity")
                        .WithMany("ItineraryOriginCities")
                        .HasForeignKey("OriginCityId")
                        .HasConstraintName("itinerary_origin_city_id_fkey");

                    b.HasOne("GoBest.Models.User", "User")
                        .WithMany("Itineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("itinerary_user_id_fkey");

                    b.Navigation("DestCity");

                    b.Navigation("OriginCity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoBest.Models.ItineraryLeg", b =>
                {
                    b.HasOne("GoBest.Models.Itinerary", "Itinerary")
                        .WithMany("ItineraryLegs")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("itinerary_leg_itinerary_id_fkey");

                    b.HasOne("GoBest.Models.SeatType", "SeatType")
                        .WithMany("ItineraryLegs")
                        .HasForeignKey("SeatTypeId")
                        .HasConstraintName("itinerary_leg_seat_type_id_fkey");

                    b.HasOne("GoBest.Models.Service", "Service")
                        .WithMany("ItineraryLegs")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("itinerary_leg_service_id_fkey");

                    b.Navigation("Itinerary");

                    b.Navigation("SeatType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GoBest.Models.Service", b =>
                {
                    b.HasOne("GoBest.Models.Company", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("service_company_id_fkey");

                    b.HasOne("GoBest.Models.Station", "DestStation")
                        .WithMany("ServiceDestStations")
                        .HasForeignKey("DestStationId")
                        .HasConstraintName("service_dest_station_id_fkey");

                    b.HasOne("GoBest.Models.Station", "OriginStation")
                        .WithMany("ServiceOriginStations")
                        .HasForeignKey("OriginStationId")
                        .HasConstraintName("service_origin_station_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("DestStation");

                    b.Navigation("OriginStation");
                });

            modelBuilder.Entity("GoBest.Models.ServiceSeatInventory", b =>
                {
                    b.HasOne("GoBest.Models.SeatType", "SeatType")
                        .WithMany("ServiceSeatInventories")
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("service_seat_inventory_seat_type_id_fkey");

                    b.HasOne("GoBest.Models.Service", "Service")
                        .WithMany("ServiceSeatInventories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("service_seat_inventory_service_id_fkey");

                    b.Navigation("SeatType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GoBest.Models.Station", b =>
                {
                    b.HasOne("GoBest.Models.City", "City")
                        .WithMany("Stations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("station_city_id_fkey");

                    b.Navigation("City");
                });

            modelBuilder.Entity("GoBest.Models.Booking", b =>
                {
                    b.Navigation("BookingLegs");
                });

            modelBuilder.Entity("GoBest.Models.City", b =>
                {
                    b.Navigation("ItineraryDestCities");

                    b.Navigation("ItineraryOriginCities");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("GoBest.Models.Company", b =>
                {
                    b.Navigation("CompanyMaintainers");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("GoBest.Models.Itinerary", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ItineraryLegs");
                });

            modelBuilder.Entity("GoBest.Models.SeatType", b =>
                {
                    b.Navigation("BookingLegs");

                    b.Navigation("ItineraryLegs");

                    b.Navigation("ServiceSeatInventories");
                });

            modelBuilder.Entity("GoBest.Models.Service", b =>
                {
                    b.Navigation("BookingLegs");

                    b.Navigation("ItineraryLegs");

                    b.Navigation("ServiceSeatInventories");
                });

            modelBuilder.Entity("GoBest.Models.Station", b =>
                {
                    b.Navigation("ServiceDestStations");

                    b.Navigation("ServiceOriginStations");
                });

            modelBuilder.Entity("GoBest.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CompanyMaintainers");

                    b.Navigation("Itineraries");
                });
#pragma warning restore 612, 618
        }
    }
}
